# Generated by Django 4.2.8 on 2023-12-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='post_images',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
