# Generated by Django 4.2.8 on 2023-12-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_profile_first_name_alter_profile_last_name'),
        ('Post', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='file',
            field=models.FilePathField(default='', verbose_name='File Field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='Post.tag', verbose_name='Post Tags'),
        ),
    ]
