# Generated by Django 4.2.8 on 2023-12-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_remove_postimage_image_postimage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='file',
            field=models.FileField(upload_to='', verbose_name='File Field'),
        ),
    ]
