# Generated by Django 4.2.8 on 2023-12-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_post_location_alter_postimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='file',
        ),
        migrations.AddField(
            model_name='postimage',
            name='file_name',
            field=models.CharField(default='', verbose_name='File name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Post.tag', verbose_name='Post Tags'),
        ),
    ]
