# Generated by Django 4.2.7 on 2023-12-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
    ]
